export const GET_MOVIES_RESPONSE = 'GET_MOVIES_RESPONSE';
export const GET_MOVIE_RESPONSE = 'GET_MOVIE_RESPONSE';
export const ADD_NEW_MOVIE_RESPONSE = 'ADD_NEW_MOVIE_RESPONSE';
export const UPDATE_EXISTING_MOVIE_RESPONSE = 'UPDATE_EXISTING_MOVIE_RESPONSE';
export const DELETE_MOVIE_RESPONSE = 'DELETE_MOVIE_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
